version : "3.8"

services:
  app_coink:
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=coink
      - MYSQL_PASSWORD=coink
      - MYSQL_DATABASE=coinktable
    ports:
      - 3306:3306